name: Build and Publish Docker Image
on:
  push:
    paths:
      - ".github/**"
      - "src/**"
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Build:


