# .github/workflows/link-analyse-test.yml
name: Lint, Analyse and Test
on:
  push:

jobs:
  Say-Hello:
    name: Say Hello Mundo!
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Mundo!"